### ISSUE TITLE
 Low PARTICIPATION (33%) and 0 votes 

### ISSUE THREAD

**Issue by annamariaGG** [aptos-labs/aptos-ait2#10]
Liveness 100%, Participation 33%, Votes 0
Address: 0x0548e2a9701d04f7af642a9b2e1260288600862302386594485a3b4f2f1812ee
Updated validator image to testnet_41e4066d6500df4c026407b1b461d1581f13c360 and restarted node

aptos_consensus_current_round 1181
aptos_consensus_proposals_count 38

[aptos_consensus_vote_nil_count 179

aptos_connections{direction="inbound",network_id="Validator",peer_id="0548e2a9",role_type="validator"} 36
aptos_connections{direction="outbound",network_id="Validator",peer_id="0548e2a9",role_type="validator"} 165

sync is normal

**Comment by annamariaGG** [comment]
At the moment, 50% and 1570 votes. I'm just interested in what caused such a low start

**Comment by sherry-x** [comment]
participation is depends on your node proposal, if your node previously was not working properly, you will have low participation rate, if you see it increasing then it's good
