### ISSUE TITLE
InvalidOrderedLedgerInfo

### ISSUE THREAD

**Issue by fontm2** [aptos-labs/aptos-ait2#12]
Hi, unfortunately my node seems to be to slow as i do not have 100% participation, despite neither CPU/RAM/Disk usage is very high, also Network I/O is under what is published on VPS benchmarking sites. My proposal count increases very slowly compared to what it did prior the update. Also prior the update, my participation rate was increasing, now it is decreasing. Is there something not ok with my setup? I have many of those errors mentioned below.

```Jul 14 03:49:05 vmi829222.contaboserver.net aptos-node[273099]: 2022-07-14T01:49:03.964679Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or at least one of executed_state_id, version, or epoch_state are not dummy value: LedgerInfo: [commit_info: BlockInfo: [epoch: 57, round: 3522, id: 84eff716, executed_state_id: a2c62362, version: 794155, timestamp (us): 1657763339743236, next_epoch_state: None]]","event":"error","name":"sign_commit_vote"}```
 and 
```Jul 14 03:49:05 vmi829222.contaboserver.net aptos-node[273099]: 2022-07-14T01:49:03.964690Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit_info: BlockInfo: [epoch: 57, round: 3522, id: 84eff716, executed_state_id: a2c62362, version: 794155, timestamp (us): 1657763339743236, next_epoch_state: None]]")```

**Comment by teenu4** [comment]
`Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720851Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720866Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720876Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720883Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720892Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720899Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720912Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720922Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720932Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720939Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720947Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720956Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720964Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720974Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720983Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720990Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.720998Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721004Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721012Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721025Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721034Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721040Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721048Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721054Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721074Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721082Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721090Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721100Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721109Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721116Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721128Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721136Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721144Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721159Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721168Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721175Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721184Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721196Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721206Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721216Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721227Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721233Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721245Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721252Z [consensus] ERROR consensus/safety-rules/src/safety_rules.rs:473 {"error":"Invalid Ordered LedgerInfoWithSignatures: Empty or a>
Jul 14 03:43:30 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:29.721261Z [consensus] ERROR consensus/src/experimental/buffer_manager.rs:311 Signing failed InvalidOrderedLedgerInfo("LedgerInfo: [commit>
Jul 14 03:43:49 teenu4k.example.com systemd-journald[265]: Suppressed 5954 messages from aptosd.service
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.696280Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"4b94a970>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.696388Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"f06bbf01>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.696783Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"a99a53b3>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.696831Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"28c0c0b5>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.696869Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"8e8b1a68>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.730339Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"0242bf2b>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.730424Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"4ba5c50b>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.730479Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"5833906d>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.730531Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"61150585>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.730594Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"ff1edbd3>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.743278Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"25640da7>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.743360Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"06c09732>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.778650Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"6c2398f7>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.778741Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"618aabd7>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.847687Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"2cde4fec>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.847766Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"2a6cb5cf>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.847827Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"be0992ad>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.847871Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"1ad4dc0e>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.847911Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"52dbd95e>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.847960Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"009f6f87>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.848046Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"795e1078>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.848100Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"21ebf969>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.848149Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"60d5890f>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.898032Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"9c82b97f>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.898334Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"da4372f6>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.937176Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"80beda82>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.937281Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"95bc336f>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.937335Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"e20f2be6>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.937390Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"c93715ae>
Jul 14 03:43:49 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:49.958918Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"455975ba>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.011170Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"6f409c8b>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.011268Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"a647d289>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.011314Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"5ec8cb94>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.011369Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"b7461f6e>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.011417Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"574bfd10>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.011465Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"4d9f6c8e>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.011506Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"0078e6da>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.050381Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"7cc07805>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.050517Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"b0a5baa1>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.050569Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"24a05de3>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.050614Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"7165b383>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.066438Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"9239e575>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.105179Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"2f0ec01a>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.105280Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"c2265e43>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.105342Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"c9e4024c>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.105402Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"939c07e5>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.105447Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"d1013439>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.105495Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"89c346d1>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.161968Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"65ce76e2>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.162070Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"81be8539>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.162123Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"1ccf907d>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.162171Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"b4db44fc>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.162220Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"86381a8d>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.162276Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"156e5f56>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.162320Z [consensus] INFO consensus/src/round_manager.rs:662 {"epoch":59,"event":"ReceiveVote","is_timeout":true,"remote_peer":"46161f67>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.198877Z [consensus] INFO consensus/src/round_manager.rs:222 {"epoch":59,"event":"NewRound","reason":"Timeout","round":3144}
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.458813Z [consensus] INFO consensus/src/round_manager.rs:286 {"block_hash":"e6a767c3b0d4d6a96751fd75ba6d285c39c12c5e0c7dce62232ed6e2a34b>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.459544Z [consensus] INFO consensus/src/round_manager.rs:334 Local state SyncInfo[certified_round: 3142, ordered_round: 3141, timeout ro>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.497455Z [consensus] INFO consensus/safety-rules/src/safety_rules.rs:207 {"event":"update","last_voted_round":3144,"name":"last_voted_ro>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.497475Z [consensus] INFO consensus/safety-rules/src/safety_rules.rs:136 {"event":"update","name":"one_chain_round","preferred_round":31>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.497478Z [consensus] INFO consensus/safety-rules/src/safety_rules.rs:144 {"event":"update","name":"preferred_round","preferred_round":31>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.497838Z [consensus] INFO consensus/safety-rules/src/safety_rules.rs:468 {"event":"success","name":"construct_and_sign_vote_two_chain",">
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.500857Z [consensus] INFO consensus/src/round_manager.rs:569 Vote: [vote data: VoteData: [block id: e6a767c3, epoch: 59, round: 3144, ti>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.501454Z [consensus] INFO execution/executor/src/block_executor.rs:104 execute_block {"block_id":"32a455948cb2ee2138f702bb366769c6261fd1>
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.522123Z [consensus] INFO consensus/safety-rules/src/safety_rules.rs:468 {"event":"success","name":"sign_commit_vote"}
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.522165Z [consensus] ERROR consensus/src/network_interface.rs:179 Peer not connected
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.522172Z [consensus] ERROR consensus/src/network_interface.rs:179 Peer not connected
Jul 14 03:43:50 teenu4k.example.com cargo[224794]: 2022-07-14T03:43:50.522179Z [consensus] ERROR consensus/src/network_interface.rs:179 Peer not connected
`

**Comment by JoshLind** [comment]
Thanks @fontm2 and @teenu4.

To follow up, can you provide the following:
- Your node setup, e.g., if you're running it from source, Docker or Terraform (and the source code version, e.g., the image tag or branch).
- A description of the issues you're facing and how long they've been occurring.
- **Important**: The logs for your node (going as far back as possible). Without detailed logs we'll be unlikely to debug the issue.
- Please can you also enable debug logs for the node. You can do this by updating your node configuration file (e.g., `validator.yaml`) by adding the following and restarting your node:
```
 logger:
   level: DEBUG
```
- Please also include any other information you think might be useful and whether or not restarting your validator helps.

@zekun000, should this issue be resolved with the latest update? Or is it still a known issue?

**Comment by teenu4** [comment]
Hi @zekun000 , great news!
I'm using source code so I'm updating right now and will update this comment with results.

**Comment by sherry-x** [comment]
Please upgrade and feel free to file the issue again if you still see problem after the upgrade
