### ISSUE TITLE
Unable to fetch peers to poll - AIT2

### ISSUE THREAD

**Issue by levicook** [aptos-labs/aptos-ait2#16]
I'm trying to connect to AIT2 and am unable to connect with peers. The first and apparent root error I'm seeing is:

```
2022-07-14T13:12:05.147862Z [aptos-data-client] ERROR state-sync/aptos-data-client/src/aptosnet/mod.rs:690 {"error":"DataIsUnavailable(\"No connected AptosNet peers!\")","event":"peer_polling_error","message":"Unable to fetch peers to poll!","name":"storage_summary_request"}
```

Validator logs from startup:
https://gist.githubusercontent.com/levicook/1807fc4e8822b6e4cad0c188f2fb52f9/raw/0863c9988f1d4cd1d281afe4a979fa80b3b901b7/validator.log

Someone mentioned that this could be because I'm connecting to chain_id `40` instead of `41`.  I updated layout.yaml and restarted (with a new data directory) and appear to still be on chain_id 40. Unsure if that's a root cause issue or not, but FYI

**Comment by levicook** [comment]
The files I'm using came from urls shared in Slack (which might not be right). Will look for the correct files in the repo.

If convenient, mind sharing / confirming expected sums? 

```bash
$ md5sum  testnet/genesis.blob testnet/waypoint.txt
b7df98c13de6a15603a53d187a3dcb8c  testnet/genesis.blob
1e1ee3fba64b2b0cf6665f37cb69c02a  testnet/waypoint.txt
```

**Comment by levicook** [comment]
Found and will try these (they have different sums too)

```
ait2@aptos-ait2-validator:~$ find ~/aptos-core/ -name 'genesis.blob' -o -name 'waypoint.txt'
~/aptos-core/terraform/helm/aptos-node/files/test-data/waypoint.txt
~/aptos-core/terraform/helm/aptos-node/files/test-data/genesis.blob

ait2@aptos-ait2-validator:~$ md5sum ~/aptos-core/terraform/helm/aptos-node/files/test-data/waypoint.txt ~/aptos-core/terraform/helm/aptos-node/files/test-data/genesis.blob
c4020ad5441d86dccad246b620b1d933  ~/aptos-core/terraform/helm/aptos-node/files/test-data/waypoint.txt
8e1dcffc8fc1a4a3cbef805b1dd940d4  ~/aptos-core/terraform/helm/aptos-node/files/test-data/genesis.blob
```

**Comment by justlstn** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/10776006/179050317-0bc01ec7-16c4-4b88-b578-b8cbf5605151.png">

**Comment by levicook** [comment]
Used the files I found in the repo (haven't compared sums) and that led to a hard crash:
https://gist.github.com/levicook/1cd1e3eb9df5c817a865a3db93be9130

**Comment by levicook** [comment]
Those are different too (somewhat expected)

```
$ md5sum ~/testnet/genesis.blob ~/testnet/waypoint.txt
8e1dcffc8fc1a4a3cbef805b1dd940d4  /home/ait2/testnet/genesis.blob
c4020ad5441d86dccad246b620b1d933  /home/ait2/testnet/waypoint.txt
```

Now I just need to get hands on the correct genesis files, lol

**Comment by levicook** [comment]
Finally got hands on the correct files. Off and running; closing the issue, thanks for the assist!!

```
$ curl 127.0.0.1:9101/metrics 2> /dev/null | grep "aptos_connections{.*\"Validator\".*}"
aptos_connections{direction="inbound",network_id="Validator",peer_id="87d59797",role_type="validator"} 1
aptos_connections{direction="outbound",network_id="Validator",peer_id="87d59797",role_type="validator"} 17
```
