### ISSUE TITLE
validator stop syncing

### ISSUE THREAD

**Issue by z83166588** [aptos-labs/aptos-ait2#17]
Hello admin.
I'm using Docker to run my validator, current tag is testnet_41e4066d6500df4c026407b1b461d1581f13c360.
it stop syncing after running several hours. It seems to be working fine for a long time after the new version was updated yesterday, but it stop again earlier today. I restarted the node, don't know if the logs now help. I can enable debug logs for the node and reset the node if needed.
![05N`_0W4JR3)@SBV(F0YM%H](https://user-images.githubusercontent.com/73794714/179026791-02a9aeeb-0498-4d6c-9435-45a11b68def4.png)
[824f6e9a26a7ae0317132178ca7fb921683e283a4eab72fdd51df43134564f19-json.zip](https://github.com/aptos-labs/aptos-ait2/files/9113475/824f6e9a26a7ae0317132178ca7fb921683e283a4eab72fdd51df43134564f19-json.zip)

**Comment by zekun000** [comment]
please try out new update testnet_95dae1f1221571c4cbca8f9a9c7b6e0182603c9c

**Comment by sherry-x** [comment]
Please upgrade and feel free to file the issue again if you still see problem after the upgrade

**Comment by z83166588** [comment]
I have upgrade the docker, tag testnet_a0290ec4b34d916ab51e874ae210cf6175a4fa72. If validator have the same problem, I will notify here in time
