### ISSUE TITLE
Traffic and free space consumption

### ISSUE THREAD

**Issue by maxmailman** [aptos-labs/aptos-ait2#19]
Hello, the node consumes a large amount of traffic, here are the monitoring data:
![изображение](https://user-images.githubusercontent.com/8423864/179130144-91fdc8f3-c749-4f63-bfa9-3ae4fa352f1d.png) 
![изображение](https://user-images.githubusercontent.com/8423864/179132091-2fb16964-8942-4fab-ba02-0ee19d5cf463.png)

Also, I had to limit the size of the logs in the container. If they are not limited, then the node, first, fills all the allocated RAM, and then very quickly the disk space.
First, the aptos_consensus_current_round indicator starts to stop - it stops resetting, after which the disk is already filling up. Logs, unfortunately, I can’t attach, because I had to clean the disk, and limiting the size of the logs solved the problem:
![изображение](https://user-images.githubusercontent.com/8423864/179130989-dfc1d957-0583-49f2-81ea-2294973d65fd.png)

**Comment by sherry-x** [comment]
Hey @maxmailman thanks for sharing the information with us!

Did you see the network bandwidth usage consistently at 61Mb/s? Have you checked if your node is under attack?
As for disk space, yes please setup some log rotation so that you don't fill the disk space all by logs. how much disk space did you setup for your node?

**Comment by maxmailman** [comment]
> 

Traffic consumption is constant. I read the metrics within the network, only ports 6180 and 6181 are forwarded to the Internet - according to your recommendations. The place is now occupied by 15GB out of 539. Before the magazine limit, the place could end in 3-4 hours, and traffic consumption grew to 150-160 mb / s

**Comment by maxmailman** [comment]
The last update reduced traffic consumption by about 30%, I will wait for further improvements.
![изображение](https://user-images.githubusercontent.com/8423864/179154077-0fe71bb8-a9e4-40a6-9d32-effefccb28b5.png)

**Comment by maxmailman** [comment]
Today the node stopped working, the aptos_consensus_current_round indicator stopped growing, and then fell, I am attaching the available logs.
![изображение](https://user-images.githubusercontent.com/8423864/179335881-7b6ae774-d533-438b-a4f5-505a826ad0c7.png)
[Docker.zip](https://github.com/aptos-labs/aptos-ait2/files/9125021/Docker.zip)

**Comment by maxmailman** [comment]
Now the aptos-aptos_consensus_current_round indicator does not increase at all.

**Comment by maxmailman** [comment]
[3722278bcc73531fa69c1b7f6c851172032b74b295b2f359328939bb5bd6b47a-json.zip](https://github.com/aptos-labs/aptos-ait2/files/9125176/3722278bcc73531fa69c1b7f6c851172032b74b295b2f359328939bb5bd6b47a-json.zip)

**Comment by maxmailman** [comment]
The indicator began to grow, it seems there were problems with communication with the bootstrap node.

**Comment by maxmailman** [comment]
I close the topic, everything works. I hope I will have time to raise the statistics :) Good luck to you!

**Comment by maxmailman** [comment]
![изображение](https://user-images.githubusercontent.com/8423864/179655832-94b56d2f-f506-428b-8c2c-7aab261e6efa.png)

Same problem again, didn't change anything. Before that everything worked perfectly. Restarting the container, restarting the server does not help. Participation also began to fall. I send logs.
[67264b5417d36deb4c5659cd318c5b55f4fe53fcfa074343f10010db4802282c-json.zip](https://github.com/aptos-labs/aptos-ait2/files/9137103/67264b5417d36deb4c5659cd318c5b55f4fe53fcfa074343f10010db4802282c-json.zip)

**Comment by maxmailman** [comment]
Again began to grow, I take off the logs.
![изображение](https://user-images.githubusercontent.com/8423864/179664769-42b58ae9-809f-4d24-b2ca-615c33128a4c.png)
[6fc3e5e34d240686374d755d3e222a0d1d73bf2483427b1d12199f13c5057e1b-json.zip](https://github.com/aptos-labs/aptos-ait2/files/9137468/6fc3e5e34d240686374d755d3e222a0d1d73bf2483427b1d12199f13c5057e1b-json.zip)

**Comment by maxmailman** [comment]
Another problem, I'm attaching the available logs.
![изображение](https://user-images.githubuserco
[0f5de701da60d1ea84afa84649104e183c58110326ea3bcdbe46baed9639e4ff-json.zip](https://github.com/aptos-labs/aptos-ait2/files/9156481/0f5de701da60d1ea84afa84649104e183c58110326ea3bcdbe46baed9639e4ff-json.zip)
ntent.com/8423864/180139462-d3ad0df4-57fd-484e-bee2-336bfd778edc.png)

**Comment by maxmailman** [comment]
The figures are still not growing. Restarting the hardware does nothing.
[d4565ad3ad8efa36850f0959c8decd3e5425f65e2b985cfd18f5acdd5451e130-json.zip](https://github.com/aptos-labs/aptos-ait2/files/9164801/d4565ad3ad8efa36850f0959c8decd3e5425f65e2b985cfd18f5acdd5451e130-json.zip)

**Comment by maxmailman** [comment]
I restored the node from the backup, at least something started to work. I hope in the next testnet you will not give all preferences to nodes, which, in principle, cannot have problems due to their proximity to each other. It is precisely those nodes that are really far away from the main mass that suffer.
