### ISSUE TITLE
the participation rate does not rise above 89%

### ISSUE THREAD

**Issue by Monopolisto** [aptos-labs/aptos-ait2#22]
Contabo 
cpu-10
ram-60GB
SSD-1600GB
port-1000 Mbit/s
IMAG_TAG:testnet_a0290ec4b34d916ab51e874ae210cf6175a4fa72
The validator is installed using Docker

I updated the characteristics of my server and increased the bandwidth yesterday, for those indicated above,the validator began to rise in the rating, but the percentage of participation does not rise above 89% the problem was earlier on the smaller characteristics of the server then the percentage of participation did not rise above 88% then fell to 75% now the range that I noticed is 86-89% 
I would like to solve this problem.
IMAG_TAG:testnet_a0290ec4b34d916ab51e874ae210cf6175a4fa7
Logs attached
[log.txt](https://github.com/aptos-labs/aptos-ait2/files/9119058/log.txt)
[log2.txt](https://github.com/aptos-labs/aptos-ait2/files/9119195/log2.txt)

**Comment by terryxsq** [comment]
im having similar issue. probably because low proposal per hour. i have around 5-6proposal per hour,im stuck at around 77%. and it is sometimes dropping a few %.
