### ISSUE TITLE
Fullnode connection over VFN and Public networks

### ISSUE THREAD

**Issue by xorgal** [aptos-labs/aptos-ait2#23]
Seems like Validator is not able to connect to fullnode over VFN. However, the fullnode has no issues to discover and connect to validator.
```
aptos_connections{direction="inbound",network_id="vfn",peer_id="0d956208",role_type="full_node"} 0
aptos_connections{direction="outbound",network_id="vfn",peer_id="0d956208",role_type="full_node"} 1
```
Can observe some RPC Timeouts in fullnode logs when it tries to discover and establish connection with validator. See attached logs for details.

Also, onchain discovery for "Public" network seems like not very efficient. Upon joining testnet fullnode managed to receive several inbounds connections (with maximum observed 6 inbound nodes connected) but after applying another hotfix and restarting the node the counter obviously was reset and since that I didnt observe that Public network counter for inbound connections is rising.

Hopefully, it helps debugging. Cheers!
[fullnode.txt](https://github.com/aptos-labs/aptos-ait2/files/9122726/fullnode.txt)

**Comment by sherry-x** [comment]
This is fine, connections are made either inbound or outbound, any direction successfully is okay

**Comment by xorgal** [comment]
I understand that it's not a big deal. Just curious how it works in test mode. Something to consider in future, perhaps there shall be some requirements to have a full node running in future testnets as in live network there is no chance that validator shall be exposed and there always have to be at least couple of nodes running in each vfn. Ideal is to have at least one node but probably more running in both vfn and public networks to have a barrier between validators and those seeking for api requests. And of course it also a huge benefit towards decentralized network. Thanks for reply and have a nice weekend ahead! :)
