### ISSUE TITLE
node doesn't show in explorer

### ISSUE THREAD

**Issue by ybzxaa** [aptos-labs/aptos-ait2#3]
i have checked every status of the node, nothing is wrong, but it still is  not  shown in the explorer...
address: 0xca4a2917b00922ee32a58725314dc8e71c5ef419ebc35abae50a21a2ae4d0e4b

![image](https://user-images.githubusercontent.com/27861517/178818219-2212c5a6-93eb-4577-9a37-a2765a6cda88.png)

**Comment by pierreneter** [comment]
Please check my node address too: `0xcca3338dfda1b5e9bab0d744c3b50a9a24e3fe55bba48917307e813a4535e034` (it is the replacement node for the old address `0xa43b4fb048098cb76bd7abb448d80f75ca1df33b03045923e913d3a2d4735654`) thanks so much

**Comment by sherry-x** [comment]
@pierreneter yours is in there

**Comment by pierreneter** [comment]
thanks @sherry-x finally saw it

**Comment by MangoGan** [comment]
Hello @sherry-x  , same problem with me,  Can I ask a favour?
My address: 0x081cdf5823dc4956a9976b0ef70999757645b60d089e39518d5e7d64274d2254
Issue: https://github.com/aptos-labs/aptos-ait2/issues/13

**Comment by sherry-x** [comment]
Both of you are showing now
