### ISSUE TITLE
Low PARTICIPATION (14%)

### ISSUE THREAD

**Issue by timus9** [aptos-labs/aptos-ait2#4]
Liveness 100% and Participation 14%
Check my node please
Adress: 0x19161a6c41efac3f3c1b581cbeabf156fe6c9ae026e39eb9e016241d36e3b8cb
Updated validator image to testnet_41e4066d6500df4c026407b1b461d1581f13c360 and restarted node
I used this guide - https://github.com/kj89/testnet_manuals/tree/main/aptos/AIT2
Lock up duration - 119h

**Comment by sherry-x** [comment]
Dashboard will reset soon, please come back again if that still doesn't show 100%

**Comment by sherry-x** [comment]
Participation rate low means your node is not actively proposing, usually because it's too slow, network bandwidth not enough etc.

**Comment by JoshLind** [comment]
Thanks @timus9. 

To follow up, can you provide the following:
- The logs for your node (going as far back as possible). Without detailed logs we'll be unlikely to debug the issue.
- Please can you also enable debug logs for the node. You can do this by updating your node configuration file (e.g., `validator.yaml`) by adding the following and restarting your node:
```
 logger:
   level: DEBUG
```
- Please also include any other information you think might be useful and whether or not restarting your validator helps.

**Comment by timus9** [comment]
Hi!
Participation is 74% now. The amount of votes is incresing. Is it normal or there should be 100% everywhere?
Thanks in advance for your answer

**Comment by sherry-x** [comment]
we have another hot-fix to resolve the issues couple nodes observed (node panic, state sync stuck). please upgrade your node to ensure the reliability, this is important to maintain your liveness and participation:
- If using source code, checkout the latest of testnet branch, make sure you are on commit 95dae1f1221571c4cbca8f9a9c7b6e0182603c9c, and restart your node. (No need to wipe data or update genesis)
- If using docker, update your validator image to testnet_95dae1f1221571c4cbca8f9a9c7b6e0182603c9c and restart your node
- If using terraform, update your image_tag to testnet_95dae1f1221571c4cbca8f9a9c7b6e0182603c9c, and terraform apply.

**Comment by timus9** [comment]
> Thanks @timus9.
> 
> To follow up, can you provide the following:
> 
> * The logs for your node (going as far back as possible). Without detailed logs we'll be unlikely to debug the issue.
> * Please can you also enable debug logs for the node. You can do this by updating your node configuration file (e.g., `validator.yaml`) by adding the following and restarting your node:
> 
> ```
>  logger:
>    level: DEBUG
> ```
> 
> * Please also include any other information you think might be useful and whether or not restarting your validator helps.

That is my logs with error.
https://gyazo.com/0b3beef7eabdc1763913ea340345553c
Do somebody knows how to make participation=100?
