### ISSUE TITLE
Proposal count 0 after update

### ISSUE THREAD

**Issue by DJ-MGMT** [aptos-labs/aptos-ait2#9]
Hi! Our node is still not showing in the Validator Status list. Everything seems OK after the last update, node is constantly syncing throughout the epoch but proposal count stays 0. Can you help us troubleshoot this?

We are node 0x624988d19577a16163444fab1d57f3a9bdeb9f509938a2c8ca9bae39773725fd

[logs.txt](https://github.com/aptos-labs/aptos-ait2/files/9106327/logs.txt)

**Comment by sherry-x** [comment]
@zekun000 @msmouse @ikabiljo

**Comment by DJ-MGMT** [comment]
OK, log is actually not as flooded with the "BlockNotFound" error as it was prior to the update. There was a bout of them as can be seen from the second log I uploaded but the node seems healthier now (at least it's doing more than just feeding that error!)

Original problem remains, 
curl 127.0.0.1:9101/metrics 2> /dev/null | grep aptos_consensus_proposal_count
and
curl 127.0.0.1:9101/metrics 2> /dev/null | grep "aptos_connections{."Validator".}"

give me no results...

**Comment by DJ-MGMT** [comment]
curl 127.0.0.1:9101/metrics 2> /dev/null | grep aptos_state_sync_version | grep type
aptos_state_sync_version{type="applied_transaction_outputs"} 717435
aptos_state_sync_version{type="executed_transactions"} 717435
aptos_state_sync_version{type="synced"} 717435
aptos_state_sync_version{type="synced_epoch"} 54

**Comment by DJ-MGMT** [comment]
Hi, 

Our node is not showing up in the active validators list anymore for some reason...

aptos node show-validator-set --profile ait2 | jq -r '.Result.active_validators' | grep 0x624988d19577a16163444fab1d57f3a9bdeb9f509938a2c8ca9bae39773725fd

gives no results either...

**Comment by zekun000** [comment]
we released new update, testnet_95dae1f1221571c4cbca8f9a9c7b6e0182603c9c, please update and try

**Comment by DJ-MGMT** [comment]
Looks like it's working now!
